### ISSUE TITLE
Question about Okta's own unique id vs Ecto UUID

### ISSUE THREAD

**Issue by broodfusion** [variancehq/okta-elixir#18]
Hello, 

I'd like to start off and apologize that this question is not related to the package. 
I'm researching into using Okta and running into this issue right now with the user ids.
When creating users in Okta, Okta automatically creates the id for you, something like this `00ua5gwkjo8GRNOJ44x5`. 
However in our app we're using Ecto and creating ids in UUIDv4 format, and Okta does not let you override the user id in UUIDv4 format.  
Have you guys ever experienced this before and found a solution?
Thank you!

**Comment by yordis** [comment]
@broodfusion 

You need to either add your Ecto UUID to the Okta profile (that allow you to find in your app from Okta user) and/or add the Okta ID to your Ecto schema under some value like `field(:okta_id, :string)` or something.

Or disabled the generated ID from Ecto and you make `:okta_id` your primary ID.

I will suggest to share your schema definition so it is easier to give you an example.

**Comment by broodfusion** [comment]
@yordis Thanks for the quick response.

Here is our User schema
```elixir
defmodule MyApp.Auth.User do
  use Ecto.Schema
  import Ecto.Changeset

  alias MyApp.Comment

  @primary_key {:id, Ecto.UUID, autogenerate: true}
  @foreign_key_type Ecto.UUID

  schema "users" do
    field(:change_password, :boolean, default: false)
    field(:email, :string, default: "")
    field(:first_name, :string, default: "")
    field(:is_active, :boolean, default: false)
    field(:is_admin, :boolean, default: false)
    field(:last_name, :string, default: "")
    field(:password, :string, default: "")
    field(:roles, {:array, :string}, default: ["user"])
    field(:username, :string, default: "")

    has_many(:comments, Comment, foreign_key: :user_id, references: :id)

    timestamps(type: :utc_datetime)
  end
```

**Comment by yordis** [comment]
Add a new field

```elixir
field(:okta_uuid, :string)
```

Fill this up after you create the Okta user, and save it to the DB.

**Comment by broodfusion** [comment]
@yordis Thanks, but our point of using Okta is to utilize it's IAM feature and not have to store a user table in a database like postgres. 

In this case, would it be better to write a migration script to update all the users' id from UUIDv4 format to okta id after creating them in okta? However I find this method to be cumbersome because I would also have to update all the relational tables that reference the user id.

Looking forward to hearing your recommendation.

Thank you!

**Comment by yordis** [comment]
@broodfusion for the most part either

1. You remove the user table and use Okta ID everywhere
2. Keep your user table and add the Okta ID field to it.

🤷 Not much to do thou, I don't think to have a user table is bad at all, for the most part, you will still have a user table (since you don't want to call Okta for everything all the time) but let Okta decide authentication and provisioning of the users (like disable flags in the user model or something else).

**Comment by stueccles** [comment]
hi @broodfusion i agree with @yordis. We store the Okta ID in a column on our user table along with our other user data. This is the external ID we use when accessing the Okta API. We don't store the user password (or other credential information) in our table, that is data entirely stored in Okta and we authenticate the user using the OktaSigninWidget. This way Okta is our authentication service but doesn't act as our user directory.
